spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    username: vitalifilimonov
    password: vcglzeqeuhrrlgao
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 465
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5433/spring-aop-test?prepareThreshold=0
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    schemas: public
    locations: classpath:db
    table: flyway_version
    baseline-on-migrate: true
    baseline-version: 0
logging:
  config: classpath:logback-spring.xml
  level:
    ru:
      homework: INFO

kafka:
  topic: topic-example