spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-aop-test?prepareThreshold=0
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    schemas: public
    locations: classpath:db
    table: flyway_version
    baseline-on-migrate: true
    baseline-version: 0
logging:
  config: classpath:logback-spring.xml
  level:
    ru:
      homework: INFO